blueprint:
  name: Sync Multiple Switches
  description: Синхронизация состояния одного выключателя с несколькими другими.
  domain: automation
  input:
    master_switch:
      name: Главный выключатель
      selector:
        entity:
          domain: switch
    slave_switches:
      name: Подчинённые выключатели
      selector:
        target:
          entity:
            domain: switch
            multiple: true

trigger:
  - platform: state
    entity_id: !input master_switch

action:
  - service: switch.turn_{{ trigger.to_state.state }}
    target: !input slave_switches

mode: single
