blueprint:
  name: Sync up to 5 switches
  domain: automation
  input:
    switch_entities:
      name: Switches to sync
      selector:
        entity:
          domain: switch
          multiple: true
variables:
  switch_entities: !input switch_entities
trigger:
  - platform: state
    entity_id: !input switch_entities
condition:
  - condition: template
    value_template: "{{ trigger.to_state.state in ['on','off'] }}"
action:
  - delay: "0:00:00.50"
  - service: >
      {% if (trigger and trigger.to_state and trigger.to_state.state == 'on') %}
      switch.turn_on
      {% else %}
      switch.turn_off
      {% endif %}
    data:
      entity_id: >
        {{ switch_entities | reject('equalto', trigger.entity_id) | join(', ') }}
